name: anyio_modbus_slave
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.7.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
