name: anyio_modbus
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ^3.8.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: any
  freezed: any
  lints: any
  test: any
  very_good_analysis: any
