name: anyio
description: "AnyIO"
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

version: 1.0.0+1

environment:
  sdk: ^3.8.0

workspace:
  - packages/json_rpc_annotation
  - packages/json_rpc_builder
  - packages/protocol
  - packages/template
  - packages/service
  - packages/dart_modbus

dev_dependencies:
  melos: ^7.0.0-dev
  very_good_analysis: any
