builders:
  json_rpc_builder:
    import: "package:json_rpc_builder/builder.dart"
    builder_factories: ["jsonRcpBuilder"]
    build_extensions: {".dart": [".json_rpc_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
