name: json_rpc_builder
description: "AnyIO"
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

version: 1.0.0+1

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  json_rpc_annotation: ^1.0.0
  code_builder: ^4.10.1
  json_annotation: ^4.9.0
  source_gen: ^3.0.0
  analyzer: ^7.7.1
  build: ^3.0.1
  dart_style: ^3.1.1


dev_dependencies:
  build_runner: any
  json_serializable: any
  very_good_analysis: any
