name: anyio_service
description: "AnyIO"
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

version: 1.0.0+1

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  anyio_adapter_modbus: ^1.0.0
  anyio_template: ^1.0.0
  async: ^2.13.0
  checked_yaml: ^2.0.4
  dart_mappable: ^4.6.0
  dart_mappable_schema: ^0.1.0
  http: ^1.5.0
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  quiver: ^3.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  type_plus: ^2.1.1

dev_dependencies:
  build_runner: any
  dart_mappable_builder: ^4.6.0
  lints: any
  shelf_router_generator: ^1.1.2
  very_good_analysis: any
