name: anyio_adapter_can
description: "AnyIO"
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

version: 1.0.0+1

environment:
  sdk: ^3.8.0

resolution: workspace

dev_dependencies:
  build_runner: any
  dart_mappable_builder: any
  very_good_analysis: any
dependencies:
  anyio_modbus: ^0.1.0
  anyio_template: ^1.0.0
  dart_mappable: ^4.6.0
  meta: ^1.17.0
