name: anyio_adapter_modbus
description: "AnyIO"
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

version: 1.0.0+1

environment:
  sdk: ^3.8.0

resolution: workspace

dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  very_good_analysis: any
dependencies:
  anyio_modbus: ^0.1.0
  anyio_template: ^1.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
